### ISSUE TITLE
iobroker / ham adapter 

### ISSUE THREAD

**Issue by Thomas-sketch** [RaresAil/homebridge-levoit-air-purifier#1]
Hello,
I would like to try it, but I cannot find the adapter. I'm looking through Iobroker with the Ham adapter

**Comment by RaresAil** [comment]
Hey, what do you mean?

**Comment by Thomas-sketch** [comment]
https://github.com/ioBroker/ioBroker.ham

**Comment by RaresAil** [comment]
Can you provide the logs when it crashes?

**Comment by Thomas-sketch** [comment]
<html>
<body>


ham.0 | 2021-11-10 10:20:31.608 | error | adapter disabled
-- | -- | -- | --
host.iobroker | 2021-11-10 09:20:05.071 | info | "system.adapter.ham.0" disabled
host.iobroker | 2021-11-10 09:20:01.264 | info | Restart adapter system.adapter.ham.0 because enabled
host.iobroker | 2021-11-10 09:20:01.264 | error | instance system.adapter.ham.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker | 2021-11-10 09:20:01.263 | error | Caught by controller[4]: [11/10/2021, 9:20:00 AM] Your config.json contains an illegal accessory configuration object at position 1. Missing property 'accessory'. Skipping entry...
host.iobroker | 2021-11-10 09:20:01.263 | error | Caught by controller[3]: [11/10/2021, 9:20:00 AM] The plugin "homebridge-levoit-air-purifier" requires Node.js version of >=14.18.1 which does not satisfy the current Node.js version of v12.22.7. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
host.iobroker | 2021-11-10 09:20:01.263 | error | Caught by controller[2]: [11/10/2021, 9:20:00 AM] The plugin "homebridge-levoit-air-purifier" requires a Homebridge version of >=1.3.5 which does not satisfy the current Homebridge version of 1.3.4. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.
host.iobroker | 2021-11-10 09:20:01.263 | error | Caught by controller[1]: [11/10/2021, 9:20:00 AM] Warning: skipping plugin found at '/opt/iobroker/node_modules/homebridge-vesync-client' since we already loaded the same plugin from '/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-vesync-client'.
host.iobroker | 2021-11-10 09:20:01.263 | error | Caught by controller[1]: [11/10/2021, 9:20:00 AM] Plugin /opt/iobroker/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
host.iobroker | 2021-11-10 09:20:01.263 | error | Caught by controller[0]: [11/10/2021, 9:20:00 AM] Warning: skipping plugin found at '/opt/iobroker/node_modules/homebridge-levoitcore-client' since we already loaded the same plugin from '/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-levoitcore-client'.
ham.0 | 2021-11-10 09:20:00.737 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
ham.0 | 2021-11-10 09:20:00.737 | info | terminating
ham.0 | 2021-11-10 09:20:00.736 | info | cleaned everything up...
ham.0 | 2021-11-10 09:20:00.735 | error | The user is not logged in!
ham.0 | 2021-11-10 09:20:00.735 | error | Error: The user is not logged in! at /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-levoit-air-purifier/src/api/VeSync.ts:193:15 at /opt/iobroker/node_modules/iobroker.ham/node_modules/async-lock/lib/index.js:146:12 at AsyncLock._promiseTry (/opt/iobroker/node_modules/iobroker.ham/node_modules/async-lock/lib/index.js:280:31) at exec (/opt/iobroker/node_modules/iobroker.ham/node_modules/async-lock/lib/index.js:145:9) at AsyncLock.acquire (/opt/iobroker/node_modules/iobroker.ham/node_modules/async-lock/lib/index.js:162:3) at VeSync.getDevices (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-levoit-air-purifier/src/api/VeSync.ts:191:17) at Platform.discoverDevices (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-levoit-air-purifier/src/platform.ts:73:39) at processTicksAndRejections (internal/process/task_queues.js:97:5)
ham.0 | 2021-11-10 09:20:00.725 | error | unhandled promise rejection: The user is not logged in!
ham.0 | 2021-11-10 09:20:00.725 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
ham.0 | 2021-11-10 09:20:00.724 | debug | [11/10/2021, 9:20:00 AM] [Levoit Air Purifiers] Discovering devices...
ham.0 | 2021-11-10 09:20:00.162 | debug | Preparing Advertiser for 'Homebridge-Wrapper-Bridge 533C' using bonjour-hap backend!
ham.0 | 2021-11-10 09:20:00.159 | debug | Homebridge Wrapper Bridge publish {"username":"FF:FF:FF:FF:FF:FF","port":0,"pincode":"0","category":2,"addIdentifyingMaterial":true,"advertiser":"bonjour-hap"}
ham.0 | 2021-11-10 09:20:00.146 | debug | [11/10/2021, 9:20:00 AM] [Levoit Air Purifiers] Connecting to the servers...
ham.0 | 2021-11-10 09:20:00.145 | debug | [11/10/2021, 9:20:00 AM] Loading 1 accessories...
ham.0 | 2021-11-10 09:20:00.145 | debug | [11/10/2021, 9:20:00 AM] [Levoit Air Purifiers] Initializing LevoitAirPurifiers platform...
ham.0 | 2021-11-10 09:20:00.145 | debug | [11/10/2021, 9:20:00 AM] Loading 1 platforms...
ham.0 | 2021-11-10 09:20:00.144 | debug | [11/10/2021, 9:20:00 AM] ---
ham.0 | 2021-11-10 09:20:00.144 | debug | [11/10/2021, 9:20:00 AM] Registering platform 'homebridge-vesync-client.VesyncPlatform'
ham.0 | 2021-11-10 09:20:00.144 | debug | [11/10/2021, 9:20:00 AM] Loaded plugin: homebridge-vesync-client@0.0.3
ham.0 | 2021-11-10 09:20:00.142 | debug | [11/10/2021, 9:20:00 AM] ---
ham.0 | 2021-11-10 09:20:00.142 | debug | [11/10/2021, 9:20:00 AM] Registering platform 'homebridge-levoitcore-client.VesyncPlatform'
ham.0 | 2021-11-10 09:20:00.142 | debug | [11/10/2021, 9:20:00 AM] Loaded plugin: homebridge-levoitcore-client@0.0.17
ham.0 | 2021-11-10 09:20:00.106 | debug | [11/10/2021, 9:20:00 AM] ---
ham.0 | 2021-11-10 09:20:00.106 | debug | [11/10/2021, 9:20:00 AM] Registering platform 'homebridge-levoit-air-purifier.LevoitAirPurifiers'
ham.0 | 2021-11-10 09:20:00.105 | debug | [11/10/2021, 9:20:00 AM] Loaded plugin: homebridge-levoit-air-purifier@1.0.2
ham.0 | 2021-11-10 09:19:59.937 | debug | [11/10/2021, 9:19:59 AM] ---
ham.0 | 2021-11-10 09:19:59.937 | debug | [11/10/2021, 9:19:59 AM] Loaded 0 cached accessories from cachedAccessories.
ham.0 | 2021-11-10 09:19:59.931 | debug | [11/10/2021, 9:19:59 AM] Loaded config.json with 1 accessories and 1 platforms.
ham.0 | 2021-11-10 09:19:59.928 | debug | Remember existing Accessory Hildegard with UUID b706aead-d209-4d10-be45-af36302fb344
ham.0 | 2021-11-10 09:19:59.928 | debug | Remember existing Accessory Edeltraud with UUID 19bf6dad-d617-4f4b-ba57-b3765c50e53e
ham.0 | 2021-11-10 09:19:59.884 | debug | Initializing HAP-NodeJS v2.1.1...
ham.0 | 2021-11-10 09:19:59.802 | info | All Libraries installed/updated
ham.0 | 2021-11-10 09:19:59.802 | info | Install/Update homebridge-levoit-air-purifier
ham.0 | 2021-11-10 09:19:59.801 | info | Install/Update the following Libraries: homebridge-levoit-air-purifier
ham.0 | 2021-11-10 09:19:59.794 | info | starting. Version 4.0.2 in /opt/iobroker/node_modules/iobroker.ham, node: v12.22.7, js-controller: 3.3.18
ham.0 | 2021-11-10 09:19:59.755 | debug | statesDB connected
ham.0 | 2021-11-10 09:19:59.755 | debug | States connected to redis: 127.0.0.1:9000
ham.0 | 2021-11-10 09:19:59.752 | debug | States create User PubSub Client
ham.0 | 2021-11-10 09:19:59.752 | debug | States create System PubSub Client
ham.0 | 2021-11-10 09:19:59.748 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
ham.0 | 2021-11-10 09:19:59.747 | debug | objectDB connected
ham.0 | 2021-11-10 09:19:59.744 | debug | Objects connected to redis: 127.0.0.1:9001
ham.0 | 2021-11-10 09:19:59.740 | debug | Objects client initialize lua scripts
ham.0 | 2021-11-10 09:19:59.740 | debug | Objects create User PubSub Client
ham.0 | 2021-11-10 09:19:59.739 | debug | Objects create System PubSub Client
ham.0 | 2021-11-10 09:19:59.739 | debug | Objects client ready ... initialize now
ham.0 | 2021-11-10 09:19:59.730 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001


</body>
</html>

**Comment by RaresAil** [comment]
It looks like the plugin wasn't able to login you in the VeSync account, and also i see that it requires you to update homebridge and nodejs, homebridge can be upgraded very easily to 1.3.5, but for nodejs, i will try to lower the version of the required nodejs version to 12, and i will add a debug mode setting to can log any authentication issues

**Comment by RaresAil** [comment]
Hey @Thomas-sketch , in the other opened issue, i made a branch where i added a new branch with a debug mode, you do the same steps and show me the new logs?

https://github.com/RaresAil/homebridge-levoit-air-purifier/issues/2#issuecomment-965372001

**Comment by RaresAil** [comment]
Closed because no response was provided.
