### ISSUE TITLE
131S support

### ISSUE THREAD

**Issue by nicksaintjohn** [RaresAil/homebridge-levoit-air-purifier#10]
**Is your feature request related to a problem? Please describe:**
Hey guys, is there any reason why the LV-PUR131S cannot be supported? It strikes me that it must have all the same sensor values and speed steps, etc... so surely it's just a case of adding it to the device whitelist?

**Describe the solution you'd like:**
Could you simply add it, will it 'just work'? - Sadly, I'm not sure how to test this myself

**Describe alternatives you've considered:**
I could use another plugin I suppose, but I like that this one is so active, and regularly maintained. Alternative, I could sell my 131S and get a smaller Core... but then, I quite like my model ;)

**Additional context:**
Happy to test, and provide some debug where capable. Many thanks.

**Comment by RaresAil** [comment]
Hello. sorry for the late response, the Purifier 131S uses an old API (v1) and the 200, ... 400 Pro uses v2, in order to add support for 131S i will need to add those endpoints and i don't have a 131S purifier in order to test it

**Comment by nicksaintjohn** [comment]
Understood. I have experience with API's and intercepting various calls... Is there anything I can do to help? I have my 131S set up and working, and your plugin installed... can I maybe enable debug mode to grab some easy data? Alternatively, I can maybe proxy my phone, and save some api calls / responses? :)

**Comment by RaresAil** [comment]
You can try to use the v2, by downloading the src files, manually adding the 131S in `deviceTypes.ts` and enable debug mode and try to see if it is working

**Comment by nicksaintjohn** [comment]
ok... So Homebridge reports the following: -

`[DEBUG]: [GET DEVICES] Device List -> JSON: [{"deviceRegion":"US","isOwner":true,"authKey":null,"deviceName":"Levoit 131S Air Purifier","deviceImg":"https://image.vesync.com/defaultImages/LV_PUR131S_Series/icon_131_air_purifier_80.png","cid":"0M3mV8N_pl2cpIT7y1vaLhgyLEmlNqh5","deviceStatus":"on","connectionStatus":"online","connectionType":"wifi","deviceType":"LV-PUR131S","type":"wifi-air","uuid":"a7a373cb-86a2-48cf-bac1-5fbf3264372b","configModule":"AirPurifier131","macID":null,"mode":"auto","speed":null,"extension":null,"currentFirmVersion":null,"subDeviceNo":null,"subDeviceType":null,"deviceFirstSetupTime":"Jun 2, 2020 1:37:25 PM"}]`

I haven't seen a device appear, but I'm not sure if that's a Homebridge / IOS issue, or if I should now disable debug mode to get things working? Any thoughts on what I should do next?

**Comment by nicksaintjohn** [comment]
A little more debug (I've now disabled debug mode): -

`[11/29/2021, 5:01:58 PM] [Levoit Air Purifiers] Launched child bridge with PID 51046
[11/29/2021, 5:01:58 PM] Registering platform 'homebridge-levoit-air-purifier.LevoitAirPurifiers'
[11/29/2021, 5:01:58 PM] [Levoit Air Purifiers] Loaded homebridge-levoit-air-purifier v1.1.3 child bridge successfully
[11/29/2021, 5:01:58 PM] Loaded 0 cached accessories from cachedAccessories.0E7BEE981D19.
[11/29/2021, 5:01:58 PM] Publishing bridge accessory (name: Levoit Air Purifiers, publishInfo: {
  username: '0E:7B:EE:98:1D:19',
  port: 57948,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'bonjour-hap'
}).
[11/29/2021, 5:01:58 PM] [Levoit Air Purifiers] Connecting to the servers...
[11/29/2021, 5:01:59 PM] Homebridge v1.3.8 (HAP v0.9.7) (Levoit Air Purifiers) is running on port 57948.
[11/29/2021, 5:02:00 PM] [Levoit Air Purifiers] Discovering devices...`

Currently nothing appears in the accessories tab, so I'm guessing I've not added enough for the device to be accepted. Have added a template to the deviceMap.d.ts

`export declare enum DeviceName {
    Core400SPro = "401S",
    Core400S = "400S",
    Core300S = "300S",
    Core201S = "201S",
    Core200S = "200S",
    Core313S = "313S"
}`

...and a device name and template to the deviceName.js

`(function (DeviceName) {
    DeviceName["Core400SPro"] = "401S";
    DeviceName["Core400S"] = "400S";
    DeviceName["Core300S"] = "300S";
    DeviceName["Core201S"] = "201S";
    DeviceName["Core200S"] = "200S";
    DeviceName["Core131S"] = "131S";
})(DeviceName = exports.DeviceName || (exports.DeviceName = {}));
const deviceTypes = [
    {
        isValid: (input) => input.includes(DeviceName.Core400SPro) ||
            input.includes(DeviceName.Core400S),
        hasAutoMode: true,
        speedMinStep: 20,
        speedLevels: 5
    },
    {
        isValid: (input) => input.includes(DeviceName.Core300S),
        hasAutoMode: true,
        speedMinStep: 25,
        speedLevels: 4
    },
    {
        isValid: (input) => input.includes(DeviceName.Core201S) ||
            input.includes(DeviceName.Core200S),
        hasAutoMode: false,
        speedMinStep: 25,
        speedLevels: 4
    },
    {
        isValid: (input) => input.includes(DeviceName.Core131S) ||
            input.includes(DeviceName.Core131S),
        hasAutoMode: true,
        speedMinStep: 25,
        speedLevels: 4
    }
];
`

**Comment by RaresAil** [comment]
What i can read from the logs, this device is not compatible

**Comment by RaresAil** [comment]
A workaround is mentioned here (another issue related to 131S): https://github.com/RaresAil/homebridge-levoit-air-purifier/issues/5#issuecomment-971459299
