### ISSUE TITLE
Value expected boolean and received undefined

### ISSUE THREAD

**Issue by Pblondin123** [RaresAil/homebridge-levoit-air-purifier#103]
### Describe The Bug

Hello saw this in the log homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.

### Expected behavior

n.a

### Logs

n.a

### Plugin Config

n.a

### Plugin Version

n.a

### Homebridge Version

n.a

### Node.js Version

n.a

### NPM Version

n.a

### Operating System

n.a

**Comment by RarDFS** [comment]
Hey, this is just a warning and can be safely ignored

**Comment by RaresAil** [comment]
Hey, this is just a warning and is safe to ignore it
