### ISSUE TITLE
200S and Air Quality

### ISSUE THREAD

**Issue by nutty-daddy** [RaresAil/homebridge-levoit-air-purifier#12]
**Is your feature request related to a problem? Please describe:**
Purchased a 200S today, found this plugin and it works great! I can turn the device on/off and change fan speed with no issue. However, this device is not capable of reading air quality, and triggers the following warning:

_[12/5/2021, 11:51:19 PM] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'PM2.5 Density': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info._

**Describe the solution you'd like:**
Could you please allow the air quality sensor/PM2.5 Density to be optional? When I add the Air Purifier to to a room, the associated Air Quality sensor appears, but is unusable. 

Please let me know if you need anything further, or if I can help you with other 200S testing.

Thanks

**Comment by RaresAil** [comment]
Hey, the 200S version doesn’t have a pm2.5 sensor?

**Comment by RaresAil** [comment]
@nutty-daddy Version [1.1.4](https://github.com/RaresAil/homebridge-levoit-air-purifier/releases/tag/1.1.4) was released

**Comment by GoodyGizmos** [comment]
Hello, thank you for writing and keeping up with this plugin. I also have a 200S and v1.1.4 installed. I'm still getting a second dub-device for the Air Quality. Was v1.1.4 supposed to remove that for the 200S?

**Comment by nutty-daddy** [comment]
Hello @GoodyGizmos @RaresAil 

Thanks for the update! While this update stopped the errors in the homebridge logs regarding the pm2.5 sensor, I do have the same experience as @GoodyGizmos. I will work on providing screenshots.

**Comment by GoodyGizmos** [comment]
@nutty-daddy @RaresAil 
![image](https://user-images.githubusercontent.com/46235745/146431518-3d63a9bc-9c11-428e-9712-29d4cc1c94f3.jpeg)

**Comment by RaresAil** [comment]
@nutty-daddy @GoodyGizmos Can you provide the logs from debug mode?

**Comment by GoodyGizmos** [comment]
I enable debug logs per your instructions. How do I retrieve the log and post for you here?

**Comment by RaresAil** [comment]
@GoodyGizmos Should be in homebridge in the right up, near the restart button

**Comment by RaresAil** [comment]
@GoodyGizmos I released v1.1.6, try to upgrade to that one and see if it will work now

**Comment by GoodyGizmos** [comment]
@RaresAil Thanks. I upgraded. It's still there. I'll post the log tomorrow.

**Comment by GoodyGizmos** [comment]
@RaresAil Here is the log immediately following a Homebridge restart.
[homebridge.log.txt](https://github.com/RaresAil/homebridge-levoit-air-purifier/files/7735968/homebridge.log.txt)

**Comment by RaresAil** [comment]
@GoodyGizmos Try to reset the accessory in order to delete the cache

https://github.com/homebridge/homebridge/wiki/Connecting-Homebridge-To-HomeKit#how-to-reset-homebridge

**Comment by GoodyGizmos** [comment]
@RaresAil After reading the warning, I think I'll just live with it. Thank you though.

![image](https://user-images.githubusercontent.com/46235745/146642121-95671c04-d618-4385-bc76-0e8420663923.png)

**Comment by RaresAil** [comment]
Resetting just requires you to remove the bridge from homekit and add it again, another method is to remove the purificator from VeSync and re sync it and then restart homebridge and it will automatically reset the old pair with the purificator

**Comment by nutty-daddy** [comment]
Hey @RaresAil,

Sorry for the delay. Updated the plugin and tried both avenues to reset: removing bridge from HomeKit and removing/repairing in VeSync. Unfortunately, the Air Quality accessory still comes through after reset. I made sure to clear single cached accessory, as well. As @GoodyGizmos said, this can be lived with. Please let me know if there's anything else I can provide to help, should you still want to investigate. Thanks

**Comment by GoodyGizmos** [comment]
@RaresAil I did the VeSync method and got the same results as @nutty-daddy.

I did notice this in the log:

[18/12/2021, 12:18:21] [Levoit Air Purifiers] Adding new accessory: Air Purifier
[Air Purifier@@Filter Change Indication] Characteristic not in required or optional characteristic section for service AirPurifier. Adding anyway.
[Air Purifier@@Filter Life Level] Characteristic not in required or optional characteristic section for service AirPurifier. Adding anyway.

**Comment by nutty-daddy** [comment]
@GoodyGizmos those two lines are related to the change filter indicator light on the device and the air filter life % (you can find this in VeSync)

@RaresAil Maybe our issue is a symptom of HomeKit and not your plugin/Homebridge. I don't see anything of value in my logs in relation to the Air Quality sensor. It seems that there are few HomeKit supported Air Purifiers. I imagine they all come equipped with PM2.5 Sensors, and thus this is how HomeKit reacts to unsupported purifiers.

**Comment by kieranmjones** [comment]
I realise this issue is closed, but it seems to persist. I have just connected a 200S via this plugin and see an air quality sensor despite the 200S not having one. I see there is some code to exclude parts of the air quality sensor service but it still publishes the sensor service with a permanent "Unknown" value.

Would it be possible to adjust the plugin to not publish the air quality sensor at all for devices without a sensor? Or is the air quality sensor required for an air purifier?

**Comment by RaresAil** [comment]
Hello, i will try more to check if this can be solved or not

**Comment by RaresAil** [comment]
@kieranmjones @GitHubGoody @nutty-daddy This issue should be fixed in [v1.1.13](https://github.com/RaresAil/homebridge-levoit-air-purifier/releases/tag/1.1.13)
