### ISSUE TITLE
Purifiers stuck "Turning on..." / "Turning off..." in Home app until refresh (300S)

### ISSUE THREAD

**Issue by FlipABit** [RaresAil/homebridge-levoit-air-purifier#20]
### Describe The Bug

Tapping the purifier accessory tile in the Home app gets the tile stuck in the "Turning on..." state (or "Turning off...") until I kill the home app and reopen it or the Home app decides to refresh the state of all accessories. The purifier itself turns on quickly, but the state never updates. The logs show that the `SEND COMMAND` runs with no errors and the `GET DEVICE INFO` command runs several minutes later (when I force refresh the app). Is there any way to get it to run `GET DEVICE INFO` after setting the purifier switch on/off? 

### Expected behavior

Tapping the purifier tile in the Home app will send the "on/off" command and the Levoit plugin will periodically (within reason to not hit API limits) check the state of the accessory.

### Logs

```
[1/23/2022, 6:36:46 PM] [Levoit Air Purifiers] [DEBUG]: [SEND COMMAND] Sending command setSwitch to Bonus room purifier with ({"enabled":true,"id":0})...
[1/23/2022, 6:39:36 PM] [Levoit Air Purifiers] [DEBUG]: [GET DEVICE INFO] Getting device info...
```

### Plugin Config

```
 {
            "name": "Levoit Air Purifiers",
            "email": "redacted",
            "password": "redacted",
            "platform": "LevoitAirPurifiers",
            "enableDebugMode": true
        }
```

### Plugin Version

1.1.8

### Homebridge Version

1.4.0

### Node.js Version

16.13.2

### NPM Version

8.1.2

### Operating System

docker

**Comment by RaresAil** [comment]
Hey, so the issue is that when you send a command, it take too long to respond and is not changing the state, right?

Is the plugin running on a child bridge?

@FlipABit

**Comment by RaresAil** [comment]
@FlipABit I will temporary close this, fell free to re open it if this issue happens again
