### ISSUE TITLE
Core 300S Air Purifier not showing up in Home

### ISSUE THREAD

**Issue by Edelheid** [RaresAil/homebridge-levoit-air-purifier#26]
### Describe The Bug

I installed the plugin and entered the correct account credentials, then added the child bridge to HomeKit, but my air purifier isn't showing up. Here's the debug log:

### Expected behavior

Core 300S Air Purifier should be showing up in Home app.

### Logs

[DEBUG]: [GET DEVICES] Device List -> JSON: [{"deviceRegion":"TA","isOwner":true,"authKey":null,"deviceName":"Air Purifier","deviceImg":"https://image.vesync.com/defaultImages/Core_300S_Series/icon_300_purifier_160.png","cid":"vsokabcc28bb4587ef15d3","deviceStatus":"off","connectionStatus":"online","connectionType":"WiFi+BTOnboarding+BTNotify","deviceType":"LAP-C301S-WAAA","type":"wifi-air","uuid":"3ae8mmc6-1972-8829-83d5-b651851ca9f7","configModule":"WFON_APR_LAP-C301S-WAAA_TA","macID":"ac:1b:fb:6e:6c:a1","mode":null,"speed":null,"extension":{"airQuality":-1,"airQualityLevel":1,"mode":"manual","fanSpeedLevel":"255"},"currentFirmVersion":null,"subDeviceNo":null,"subDeviceType":null,"deviceFirstSetupTime":"Mar 5, 2022 1:33:13 AM","deviceProp":null}]

### Plugin Config

{
    "bridge": {
        "name": "Homebridge",
        "username": "0E:A5:BA:52:FD:90",
        "port": 52345,
        "pin": "942-99-555",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [
        {
            "name": "Levoit Air Purifiers",
            "email": "(removed)",
            "password": "(removed)",
            "platform": "LevoitAirPurifiers",
            "enableDebugMode": true,
            "_bridge": {
                "username": "0E:4C:91:23:50:E6",
                "port": 29410
            }
    ]
}

### Plugin Version

1.1.10

### Homebridge Version

1.3.9

### Node.js Version

14.18.1

### NPM Version

v.8.1.0

### Operating System

Raspbian Buster

**Comment by RaresAil** [comment]
Hey, thank you for reporting this issue, i will check it more in detail tomorrow. What it looks weird from the logs, is the fan speed level which is `255`, what was the speed level of the purifier at that time?

**Comment by Edelheid** [comment]
THanks for checking this out. I tried to get the debug log again and here's the changes:

`{"airQuality":-1,"airQualityLevel":1,"mode":"manual","fanSpeedLevel":"1"},"currentFirmVersion":null,"subDeviceNo":null,"subDeviceType":null,"deviceFirstSetupTime":"Mar 5, 2022 5:53:13 AM","deviceProp":null}]`

(The Core 300S was on fan level 1 during this. I believe when it was set to fan:255 the unit was "off" at the time aka it wasn't purifying.)

The strange part is the Core 300S shows up in the Home using the plugin [homebridge-levoitcore-client] which uses similar API calls, but I was hoping to use your plugin as it shows the exact value of air quality instead of just 'excellent' for example.

**Comment by RaresAil** [comment]
Hey, no need for the image, i found what's the issue, your purifier says that is model 301S, i will have to add that model in the valid models in order to can register it, that will be done tomorrow.

**Comment by Edelheid** [comment]
Oh! Thank you for that, I didn't notice the 301S. Not sure what the difference is between the 300S and 301S, but it may be regional differences. My unit is from the EU.

**Comment by Edelheid** [comment]
Thank you again for the heads-up. I experimented by adding the 301S and it's now showing up in the Home app. The only other issue(?) I find is that whenever I turn on the 301S the Home tile is stuck on "Turning on...". It does turn on the 301S just fine, but I was wondering if this is an intentional effect?

**Comment by RaresAil** [comment]
Hey, there was one more person with this issue, it could depend on location and/or internet speed, on how the server responds on the send comand. Sadly i didn't found a fix for that, and because i cant replicate that, i will try to recheck it tomorrow, but no promises.

Until i release the fix for the 301S, can you keep using your local fix and let me know if there will be any issues?

The other related issue https://github.com/RaresAil/homebridge-levoit-air-purifier/issues/22

**Comment by Edelheid** [comment]
I will continue to monitor the local fix. I'm also trying out the other plugin to try and see if anything can be done since, for some reason, that one doesn't do the "Turning on..." or "Turning off..." issue. Might find some clue or two hopefully.

**Comment by Edelheid** [comment]
After spending a bit more time monitoring the plugin I found out that I don't have to force quit the Home app to force the plugin to retrieve the status of the air purifier. I find that I can exit the Home app (swipe up) and then return again where Home app will show "Updating..." and then the status is retrieved. Strange because this is the only plugin that updates whenever I close/open the Home app without fail.

I also want to ask how is "Auto" mode activated? I find that I can only cycle through sleep, level 1, 2, and 3 using the slider. Even if I choose Auto mode in the VeSync app, if I turn off/on the air purifier in the Home app it forgets the auto mode and returns to level 1–3. Is there a way to specifically set Auto mode from the Home app?

**Comment by RaresAil** [comment]
The home app is a bit weird, you have to hold on the accessory, scroll down to accessories and there hold on again on the accessory

**Comment by RaresAil** [comment]
@Edelheid In this PR i implemented your changes from #27 for 301S and i also managed to fix the turning on and off status

**Comment by Edelheid** [comment]
Tried it and I think it's looking good so far.
