### ISSUE TITLE
Can't turn on/off my 400s in homekit.

### ISSUE THREAD

**Issue by bangelischan** [RaresAil/homebridge-levoit-air-purifier#35]
### Describe The Bug

I can't see the state and I can't turn on/off my levoit 400s within the homekit app on my iphone running IOS 15.5.
here's what I tried : 
turning the air purifier on/off with the VeSync App (it does work). 
turning the air purifier on homebridge (in the "accessory" tab", and it does work)
rebooting my iphone. (doesnt work)
rebooting my raspberry pi. doesnt work. 
I tried unpairing the child bridge and pair it again. doesnt work.
I tried unplugging/plugging the air purifier, lol. 
I also tried to empty the cached data in homebridge settings. doesnt work.

Note : I forgot to mention that it was working correctly this morning. (its not username or password related..!) 

Here are the logs :
<img width="944" alt="CleanShot 2022-07-05 at 15 39 44@2x" src="https://user-images.githubusercontent.com/46763189/177403095-c7c3e085-d77e-4a5f-84c1-2143a0744f32.png">

### Expected behavior

Air quality should display, and I should be able to turn on/off the air purifier.

### Logs

see picture above

### Plugin Config

{
    "bridge": {
        "name": "Homebridge,
        "username": "XXX",
        "port": 51991,
        "pin": "XXX",
        "advertiser": "avahi",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "LAPoB",
            "email": "XXX",
            "password": "XXX",
            "platform": "LevoitAirPurifiers",
            "_bridge": {
                "username": "XXX",
                "port": 50789
            }
        }
    ]
}

### Plugin Version

homebridge-levoit-air-purifier v1.1.13

### Homebridge Version

v1.5

### Node.js Version

v16.15.1

### NPM Version

?

### Operating System

Official Homebridge for raspberry pi Image

**Comment by bangelischan** [comment]
Turns out it was my homepod mini (hub) which was causing the problem...

**Comment by RaresAil** [comment]
Hey @bangelischan , i am curious, how did the homepod caused the problem?

**Comment by bangelischan** [comment]
And something I noticed: 

My shortcut failed with the error code : 


HMErrorDomain error 3.

(When I activate sleep mode; it was suppose to put the air purifier in sleep mode)

**Comment by RaresAil** [comment]
I don't know why is not working, maybe some DNS, router or homepod isssues
