### ISSUE TITLE
Installed in homekit as a hub but device won't show up

### ISSUE THREAD

**Issue by MelMayssonOwen** [RaresAil/homebridge-levoit-air-purifier#37]
### Describe The Bug

I've installed the plugin, first as a normal "child" of home bridge then as a hub itself. None of which successfully shows the device in HomeKit.

I can see the hub in HomeKit but not the Humidifier (200s).

### Expected behavior

Expected to see a new device in a room in HomeKit or in the accessories under hub.

### Logs

`[DEBUG]: [GET DEVICES] Device List -> JSON: [{"deviceRegion":"EU","isOwner":true,"authKey":null,"deviceName":"Humidifier","deviceImg":"https://image.vesync.com/defaultImages/deviceDefaultImages/wfon_ahm_luh-d301s-weu_eu_240.png","cid":"vsaq8cc625b4105a4e11c1241aa02454","deviceStatus":"on","connectionStatus":"online","connectionType":"WiFi+BTOnboarding+BTNotify","deviceType":"LUH-D301S-WEU","type":"wifi-air","uuid":"b27aadd3-e3d0-430e-b08f-a125132c5fa8","configModule":"WFON_AHM_LUH-D301S-WEU_EU","macID":"24:a1:60:9f:17:5e","mode":null,"speed":null,"extension":null,"currentFirmVersion":null,"subDeviceNo":null,"subDeviceType":null,"deviceFirstSetupTime":"Aug 22, 2022 8:52:18 PM","deviceProp":null}]`

### Plugin Config

`{
    "bridge": {
        "name": "Homebridge",
        "username": "",
        "port": 51245,
        "pin": ""
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Nest",
            "refreshToken": "",
            "options": [
                "HomeAway.Disable",
                "FieldTest.Enable"
            ],
            "platform": "Nest"
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "inUseThreshold": 10,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "platform": "TplinkSmarthome"
        },
        {
            "name": "eWeLink",
            "username": "",
            "password": "",
            "mode": "auto",
            "debug": false,
            "language": "en",
            "multiDevices": [
                {
                    "label": "Garage Lights",
                    "deviceId": "10015f8158",
                    "deviceModel": "dualr3_switch"
                }
            ],
            "platform": "eWeLink"
        },
        {
            "refreshToken": "",
            "platform": "Nest-cam"
        },
        {
            "name": "Levoit Air Purifiers",
            "email": "myemail",
            "password": "mypass",
            "platform": "LevoitAirPurifiers",
            "enableDebugMode": true,
            "_bridge": {
                "username": "0E:52:3D:D3:3E:C9",
                "port": 57839
            }
        }
    ],
    "disabledPlugins": [
        "homebridge-nest-cam"
    ]
}`

### Plugin Version

1.1.13

### Homebridge Version

1.5.0

### Node.js Version

v16.13.1

### NPM Version

8.3.0

### Operating System

Linux homebridge 5.10.63-v7+ #1488 SMP Thu Nov 18 16:14:44 GMT 2021 armv7l GNU/Linux

**Comment by RaresAil** [comment]
Hey, this plugin only shows air purifiers, for humidifiers you can use this one

https://github.com/pschroeder89/homebridge-levoit-humidifiers

**Comment by MelMayssonOwen** [comment]
My bad, it was in the plugin name but I apparently did not use my brain enough.
Thanks
