### ISSUE TITLE
Please suppot LAP-C401S-WJP

### ISSUE THREAD

**Issue by grandevice** [RaresAil/homebridge-levoit-air-purifier#40]
### Describe The Bug

It is recognized as a Levoit air purifier, I can turn it on and off, adjust the fan strength, and the air quality display is fine, but I can't see child lock, auto mode, or filter status.  The model is Core401S, but it is displayed as LAP-C401S-WJP.  Please support me.  Thank you.

### Expected behavior

none

### Logs

none

### Plugin Config

normal

### Plugin Version

1.1.13

### Homebridge Version

15.0

### Node.js Version

16.18.0

### NPM Version

8.19.2

### Operating System

pi os 64bit

**Comment by RaresAil** [comment]
Hello, please check https://github.com/RaresAil/homebridge-levoit-air-purifier#enabling-debug-mode and provide some logs about the device
