### ISSUE TITLE
Air Quality Levels Inconsistency

### ISSUE THREAD

**Issue by LJ-Jiahe** [RaresAil/homebridge-levoit-air-purifier#46]
### Describe The Bug

In Aqara's manual air quality is defined in 4 levels.
However, when exposed to HomeKit it shows 5 levels.
This inconsistency makes it hard to set up automations based on the actual PM 2.5 value.

<img width="1077" alt="Screenshot 2022-12-04 at 2 17 58 PM" src="https://user-images.githubusercontent.com/37913300/205513453-c95e5cb4-a5a2-485a-913e-0d8675a4877d.png">

<img width="492" alt="image" src="https://user-images.githubusercontent.com/37913300/205513486-ee43316e-44d7-4aca-a7f1-3e2b26071953.png">

### Expected behavior

Either shows 4 levels of air quality that correspond to what is provided, or exposes PM 2.5 value as a HomeKit automation trigger.

### Logs

None

### Plugin Config

        {
            "name": "Levoit Air Purifiers",
            "email": "***",
            "password": "***",
            "platform": "LevoitAirPurifiers"
        }

### Plugin Version

v1.2.0

### Homebridge Version

v1.6.0

### Node.js Version

v16.16.0

### NPM Version

8.11.0

### Operating System

Raspbian GNU/Linux 11

**Comment by RaresAil** [comment]
Hello, thank you for reporting that issue, i will see if i can remove the "Fair" from that list, since is not used, the mapping between VeSync and Home App is like this:

| VeSync | Home App |
| --- | --- |
| VERY GOOD | EXCELLENT |
| GOOD | GOOD |
| MODERATE | INFERIOR |
| POOR | POOR |

**Comment by RaresAil** [comment]
@LJ-Jiahe i created a PR that removes the fair as possible value but the home app continues to show it so there is nothing more that i can do about it
