### ISSUE TITLE
LV-PUR131S Support (API v1)

### ISSUE THREAD

**Issue by Snookieboy** [RaresAil/homebridge-levoit-air-purifier#5]
Hey,

Guessing this isn't an issue per say; but just wondering there's one other VeSync Air Purifier which is missing from support which is VeSync LV-PUR131S model.

It has all the same characteristics as the CORE purifiers using the same app and API's. Just wondering if you would kindly consider enabling support with it on a later release? Perhaps even if its in debug mode. Happy to assist with testing / access if it is something you would consider :)

**Comment by RaresAil** [comment]
Sadly the 131 model uses API v1 and this module uses v2, and to also add v1 is too much effort, but there is a workaround, to have 2 vesync accounts, 1 with the 131 and the second one with the newer versions, and to use an older plugin that uses the v1 api: https://github.com/Kwintenvdb/homebridge-vesync-client
