### ISSUE TITLE
[bug] Not Displaying the air quality on 400S

### ISSUE THREAD

**Issue by KhimairaCrypto** [RaresAil/homebridge-levoit-air-purifier#50]
### Describe The Bug

Air quality does not show in the latest build.

![400s](https://user-images.githubusercontent.com/36352470/211515352-f810e055-fa86-4e17-a682-280158a7ee0b.png)

### Expected behavior

Been able to see the air quality 

### Logs

No error messages

### Plugin Config

{
    "name": "Levoit Air Purifiers",
    "email": "my_email@my_email",
    "password": "my_password",
    "platform": "LevoitAirPurifiers"
}

### Plugin Version

1.2.1-alpha

### Homebridge Version

1.6.0

### Node.js Version

18.12.1

### NPM Version

8.19.2

### Operating System

Raspbian 1.0.39

**Comment by RaresAil** [comment]
Hey, the alpha version is to release a support for a new device and could have bugs, also the air quality is now splited into a separate accessory, so each device has 2, the purifier and air quality sensor

**Comment by KhimairaCrypto** [comment]
I switched to `1.2.1` and still not able to see the air quality

![CleanShot 2023-01-10 at 21 08 57@2x](https://user-images.githubusercontent.com/36352470/211522806-fbd1a8e7-3423-4496-b715-b4fbcb88a468.png)
