### ISSUE TITLE
Support for latest Core 300 firmware (LAP-C302S-WUSB)

### ISSUE THREAD

**Issue by kcasamento** [RaresAil/homebridge-levoit-air-purifier#51]
### Describe The Bug

Seems there was a firmware update that added a new device type to the 300 family, namely the 302S device type.  I noticed in the code only 300S and 301S are supported.  I can push a PR that adds in support.

### Expected behavior

support for device type 302S

### Logs

{}

### Plugin Config

{}

### Plugin Version

1.2.1

### Homebridge Version

1.6.0

### Node.js Version

18.13.0

### NPM Version

8.19.3

### Operating System

Ubuntu Focal Fossa (20.04.5 LTS)

**Comment by RaresAil** [comment]
Was done by @eoddc5 and it will be in version 1.2.2
