### ISSUE TITLE
Request support for Vital 200s

### ISSUE THREAD

**Issue by Jjcord** [RaresAil/homebridge-levoit-air-purifier#53]
### Describe The Bug

Thank you for your work! Please add support for new model Vital 200s. Thank you again! 

### Expected behavior

Support

### Logs

None

### Plugin Config

None

### Plugin Version

None

### Homebridge Version

None

### Node.js Version

None

### NPM Version

None

### Operating System

None

**Comment by mzdaisy89** [comment]
+1

thanks so much for your work on this plugin!

**Comment by eoddc5** [comment]
@RaresAil - wanted to also check in on vital 200s and 100s support

they are the newest models, and while not part of the “core series”,  I wonder if it’s easy enough to add on support

thanks!

**Comment by RaresAil** [comment]
@Jjcord can you post the logs with this model?

**Comment by KateLibC** [comment]
Is this what you're looking for?

`[2023-06-09, 10:19:02 p.m.] [Levoit Air Purifiers] [DEBUG]: [GET DEVICES] Device List -> JSON: [{"deviceRegion":"US","isOwner":true,"authKey":null,"deviceName":"Cleanser","deviceImg":"https://image.vesync.com/defaultImages/deviceDefaultImages/vs_wfon_apr_lap_v201s-wus_us_240.png","cid":"[removed by me]","deviceStatus":null,"connectionStatus":null,"connectionType":"WiFi+BTOnboarding+BTNotify","deviceType":"LAP-V201S-WUS","type":"wifi-air","uuid":"[removed by me]","configModule":"VS_WFON_APR_LAP-V201S-WUS_US","macID":"[removed by me]","mode":null,"speed":null,"currentFirmVersion":null,"subDeviceNo":null,"subDeviceType":null,"deviceFirstSetupTime":"Jun 9, 2023 11:02:33 PM","subDeviceList":null,"extension":null,"deviceProp":{"wifiMac":"[removed by me]","BTMac":"[removed by me]","connectionStatus":"online","workMode":"manual","powerSwitch":1,"fanSpeedLevel":4,"PM25":1,"wifiRssi":-32,"AQLevel":1}}]`

**Comment by RaresAil** [comment]
> Is this what you're looking for?
> 
> 
> 
> `[2023-06-09, 10:19:02 p.m.] [Levoit Air Purifiers] [DEBUG]: [GET DEVICES] Device List -> JSON: [{"deviceRegion":"US","isOwner":true,"authKey":null,"deviceName":"Cleanser","deviceImg":"https://image.vesync.com/defaultImages/deviceDefaultImages/vs_wfon_apr_lap_v201s-wus_us_240.png","cid":"[removed by me]","deviceStatus":null,"connectionStatus":null,"connectionType":"WiFi+BTOnboarding+BTNotify","deviceType":"LAP-V201S-WUS","type":"wifi-air","uuid":"[removed by me]","configModule":"VS_WFON_APR_LAP-V201S-WUS_US","macID":"[removed by me]","mode":null,"speed":null,"currentFirmVersion":null,"subDeviceNo":null,"subDeviceType":null,"deviceFirstSetupTime":"Jun 9, 2023 11:02:33 PM","subDeviceList":null,"extension":null,"deviceProp":{"wifiMac":"[removed by me]","BTMac":"[removed by me]","connectionStatus":"online","workMode":"manual","powerSwitch":1,"fanSpeedLevel":4,"PM25":1,"wifiRssi":-32,"AQLevel":1}}]`

Yes, i also got them for the Vital 100, after seeing the API similarities between Vital and Everest, i will support Vital models after the Everest implementation is done

**Comment by KateLibC** [comment]
Awesome. Thanks!

**Comment by C47HERINE** [comment]
I would also love for that to be supported! thanks

**Comment by afridorian** [comment]
Would love for this model to be supported as well!

**Comment by EternalRZ** [comment]
I just got a couple of these units myself. If you'd like more debug logs, I can submit mine. Just let me know~

**Comment by RaresAil** [comment]
> I just got a couple of these units myself. If you'd like more debug logs, I can submit mine. Just let me know~

Hey, join the discord server so we can chat faster

**Comment by iandecelli** [comment]
Also would love if this model were supported, thank you!

**Comment by yost** [comment]
+1 for support of the Vital line; I have a Vital 200S and would love to make use of the plugin.

New to the Homebridge community. Grateful for your work on this. Thank you!

**Comment by troydonaldson** [comment]
Also looking for Vital 200S support!

**Comment by emptyfish** [comment]
Hi all - very new (literally < 2 days) to the platform but I am trying to unwind Vital 200S support (using a fork for now just to attempt it). The API is  different so I think I get the challenge on the Vital series vs. the Core. The good news is I am to the point I can see the devices in my test instance - but control/etc. is an entirely different matter. If you have a different model in the Vital Series it would be helpful to see the debug log for it.

**Comment by slowpc1** [comment]
Came to request this model as well as just got a unit here. Seeing that the API calls don't sound to be the same, I hope some work will get added in the future for it.

**Comment by Brandawg93** [comment]
#91

**Comment by RaresAil** [comment]
This should work in v3
