### ISSUE TITLE
Support for Core PlasmaPro 300S and 600S - (Core302S and Core602S)

### ISSUE THREAD

**Issue by eoddc5** [RaresAil/homebridge-levoit-air-purifier#55]
### Describe The Bug

You have support for Core 300S and 301S models, but there is a third, Core 302S (which is the version with plasmapro)

You have support for Core 600S and 601S models, but there is a third, Core 602S (which is the version with plasmapro)

Are you able to add those model into the device list? 

### Expected behavior

NA

### Logs

NA

### Plugin Config

NA

### Plugin Version

NA

### Homebridge Version

NA

### Node.js Version

NA

### NPM Version

NA

### Operating System

NA

**Comment by eoddc5** [comment]
I made a PR for this, if you could approve it and push out a new update

**Comment by RaresAil** [comment]
The PR was merged
