### ISSUE TITLE
Core 200S Auto/Manual mode

### ISSUE THREAD

**Issue by almonde** [RaresAil/homebridge-levoit-air-purifier#63]
### Describe The Bug

The plugin presents an Auto/Manual option in HomeKit for the Core200S. However the the Core200S does not have an Auto/Manual mode, its always manual since that model does not have an air quality sensor.

### Expected behavior

Plugin doesn't expose features that are not present

### Logs

N/A

### Plugin Config

{
    "name": "Levoit Air Purifiers",
    "email": "me@myemail.com",
    "password": "my_password",
    "platform": "LevoitAirPurifiers",
    "_bridge": {
        "username": "XX:XX:XX:XX:XX",
        "port": 36967
    }
}

### Plugin Version

1.3.0

### Homebridge Version

1.60

### Node.js Version

18.13.0

### NPM Version

unsure

### Operating System

Linux Mint 21.1

**Comment by RaresAil** [comment]
Hello, thank you for reporting this issue, i will investigate it

**Comment by anxjo** [comment]
Hi,
sorry for my terrible English,
I updated node.js to version 18 .After upgrading to version 18,the levoit plugin stopped working. Can you tell me why?My Levoit model is 300S

**Comment by RaresAil** [comment]
@anxjo please open a new issue

**Comment by almonde** [comment]
Hi @RaresAil ,

I updated to 1.3.1 and even added a 2nd 200s, however the auto/manual toggle is still there,  also includes a seemingly generically labeled ‘mode’ switch. 

Do I need to remove the child bridge and start again to see the changes?

**Comment by RaresAil** [comment]
Try to restart the child bridge, but if you want to do a reset, set the password and email to "" and restart, that should reset the cache of the child bridge and than re add the devices

**Comment by almonde** [comment]
Hi @RaresAil , thanks for your work on this.

In the end I could not get the auto/manual and 'mode' toggle to disappear. I tried clearing the config as you suggested, but also tried removing the hub from Home, removing the child bridge and plugin from Homebridge then restarted and reinstalled from fresh.  It still came back for both 200S units.
<img width="568" alt="Screenshot 2023-06-25 at 9 50 23 AM" src="https://github.com/RaresAil/homebridge-levoit-air-purifier/assets/78392159/1476f559-be1a-4e0c-b721-e72bc74edc45">

**Comment by RaresAil** [comment]
I checked the documentation, and the auto/manual mode can't be removed as it is required, but i will try one more thing to see if it will work

**Comment by almonde** [comment]
Thanks, it’s no big deal, but thanks for your effort. This is a very useful plugin.
