### ISSUE TITLE
Levoit 300S

### ISSUE THREAD

**Issue by anxjo** [RaresAil/homebridge-levoit-air-purifier#65]
### Describe The Bug

Hi,
sorry for my terrible English,
I updated node.js to version 18 .After upgrading to version 18, the levoit plugin stopped working only on Homekit App.Can you tell me why?My Levoit model is 300S

### Expected behavior

Homekit app show me the purifier how Not connected

### Logs

03/05/2023, 18:54:00] [Levoit Air Purifiers] Initializing LevoitAirPurifiers platform...
[03/05/2023, 18:54:00] [Levoit Air Purifiers] Loading accessory from cache: Purificatore d’aria
[03/05/2023, 18:54:01] [Levoit Air Purifiers] Connecting to the servers...
[03/05/2023, 18:47:49] [Levoit Air Purifiers] Discovering devices...

### Plugin Config

 {
            "name": "Levoit Air Purifiers",
            "email": "xxxxxxx",
            "password": "xxxxxx",
            "experimentalFeatures": [
                "DeviceDisplay"
            ],
            "platform": "LevoitAirPurifiers"

### Plugin Version

version 1.30

### Homebridge Version

4.50.2

### Node.js Version

v18.16.0

### NPM Version

\

### Operating System

mac OS

**Comment by RaresAil** [comment]
Can you show me how it looks like from yhe home app and it is working from homebridge dashboard "?

**Comment by penskyc** [comment]
I have same issue, works fine in Homebridge dashboard. Home App just shows "No Response"

**Comment by RaresAil** [comment]
What is your homebridge version? This is a homebridge issue not plugin related

**Comment by anxjo** [comment]
Hi, thanks for the answers, my homebridge version is 4.50.2.
Today in the afternoon I will post the dashboard and home app.

**Comment by RaresAil** [comment]
Latest homebridge version is 1.6.1 which can be seen from the dashboard

**Comment by penskyc** [comment]
I am running the newest version of homebridge 1.6.1 but the issue was already happening for me on the prior version, I updated HB yesterday along with the Levoit plugin and it is no longer working. I am on 18.16 node

**Comment by RaresAil** [comment]
@penskyc 

1. is the plug-in running as child bridge
2. It is working from homebridge app?
3. Try to uninstall the plugin, run a cache reset on the plugin (check docs, should be from homebridge settings) and install it again

**Comment by anxjo** [comment]
Sorry the version is 1.6.1

**Comment by anxjo** [comment]
> Can you show me how it looks like from yhe home app and it is working from homebridge dashboard "?

So, sorry for the delay in replying. 

this is Home App
![IMG_6522F8399A63-1](https://user-images.githubusercontent.com/91833414/236491208-53c7cbfe-d512-4847-8288-39c434d2ae3b.jpeg)
Non Risponde (the translation from italian is Not connected)
For the homebridge dashboard:
Actually from the dashboard it works fine. Only through Home App does not work.

Do you have any idea what the problem could be?

**Comment by anxjo** [comment]
Good morning, 
I have a question. 
Could my problem be caused by the firmware update that required the Levoit purifier's VeSync app?

**Comment by RaresAil** [comment]
I also have the same device and latwst update and same node env and it works, try to reinstall it

**Comment by RaresAil** [comment]
> > Can you show me how it looks like from yhe home app and it is working from homebridge dashboard "?
> 
> 
> 
> So, sorry for the delay in replying. 
> 
> 
> 
> this is Home App
> 
> ![IMG_6522F8399A63-1](https://user-images.githubusercontent.com/91833414/236491208-53c7cbfe-d512-4847-8288-39c434d2ae3b.jpeg)
> 
> Non Risponde (the translation from italian is Not connected)
> 
> For the homebridge dashboard:
> 
> Actually from the dashboard it works fine. Only through Home App does not work.
> 
> 
> 
> Do you have any idea what the problem could be?
> 
> 
> 
> 

Is a homebridge issue, it should've be fixed in 1.6.1, idk why is not fixed for you, try reinstalling it
