### ISSUE TITLE
400S automation to set to Auto?

### ISSUE THREAD

**Issue by Pblondin123** [RaresAil/homebridge-levoit-air-purifier#69]
### Describe The Bug

Hi i have a when leaving home automation who will bump the Fan to 3, manual mode.  Then another first one gets home automation which sets the mode to Auto.  From checking the log in debug mode, there is not mode auto sent to the 400S, just fan speed.  I can provide more infos if needed. Any comment welcomed.

### Expected behavior

400S turns to Auto no matter the fan speed.

### Logs

N/a

### Plugin Config

N/a

### Plugin Version

Latest

### Homebridge Version

Latest

### Node.js Version

N/a

### NPM Version

N/a

### Operating System

N/a

**Comment by RaresAil** [comment]
Hey, you can trigger the home arrival automation from the app to test that is working, can you check if it works? The plugin does not impact the automation, the automation just sends requests as a normal user from the home app, maybe the automation is not triggered

**Comment by RaresAil** [comment]
I also tested on my purifier, looks like is working when also changing the speed to level 1 and mode auto, and after a test now is on auto

**Comment by Pblondin123** [comment]
Hi, i tested manually the automation, success purifier went back to normal.  I was pretty sure the automation did trigger the fan (not automation), but i am starting to have doubts :-).  I will review/retest the automation thanks.

**Comment by RaresAil** [comment]
Good luck!
