### ISSUE TITLE
iOS 17

### ISSUE THREAD

**Issue by Jjcord** [RaresAil/homebridge-levoit-air-purifier#77]
### Describe The Bug

My purifiers will not communicate with the home app on iOS 17. Anyone else? 

Also, still hoping for support for the vital 200s 🤞

### Expected behavior

None

### Logs

None

### Plugin Config

None

### Plugin Version

Latest

### Homebridge Version

Latest

### Node.js Version

Latedt

### NPM Version

Latest

### Operating System

Mac

**Comment by RaresAil** [comment]
Wdym? @Jjcord i also have ios 17 and everything works

**Comment by Jjcord** [comment]
Thanks for the tip.  I deleted the child bridge and readded it back to my home, it is now working.
