### ISSUE TITLE
Dual200S is not accurately reporting humidity it is set to

### ISSUE THREAD

**Issue by BastianZim** [RaresAil/homebridge-levoit-air-purifier#80]
### Describe The Bug

The air humidifier is set to 55% but is reporting 31%. The difference is always 24%.

### Expected behavior

It should be reporting 55%.

_Note:_ There are a couple of other issues as well. I have a Dual200S and happy to provide any info that would be helpful or create new issues for those.

### Logs

Not sure how to generate

### Plugin Config

```
{
            "name": "Levoit Air Purifiers",
            "email": "",
            "password": "",
            "experimentalFeatures": [
                "Humidifiers"
            ],
            "_bridge": {
                "username": "",
                "port":
            },
            "platform": "LevoitAirPurifiers"
        }
```

### Plugin Version

v2.0.0

### Homebridge Version

v1.7.0

### Node.js Version

v20.9.0

### NPM Version

7.5.2

### Operating System

Debian GNU/Linux Bullseye (11)

**Comment by RaresAil** [comment]
Hey, i seen that issue is only in the main view of the app, when i open the device itself it shows the correct value, in my case is set to 60 and shows 31, i think something is wrong in the home app due some configuration to allow only values from 20 to 80 i think, or 30 to 80

**Comment by BastianZim** [comment]
Yes, I'm seeing the same. In the main view, it is incorrect, and otherwise, it works.

**Comment by RaresAil** [comment]
Yep, that is an issue from Home app and I can't fix it sadly
