### ISSUE TITLE
Humidifier always shows “Rising to 35%” in home card

### ISSUE THREAD

**Issue by eoddc5** [RaresAil/homebridge-levoit-air-purifier#81]
### Describe The Bug

(I know this is new and experimental)

No matter what it is set at, the home card for the humidifier always defaults back to “rising to 35%” (even though the action is not doing that)

![IMG_9534](https://github.com/RaresAil/homebridge-levoit-air-purifier/assets/10222895/563e380f-a1e9-443f-8886-bc65f5eb581e)

if you open the card itself up, it shows the proper percentage 

![IMG_9535](https://github.com/RaresAil/homebridge-levoit-air-purifier/assets/10222895/d247aebe-1a9f-43e8-a4fd-db97b670fdf6)

### Expected behavior

Should show the correct set humidity percentage 

### Logs

Na

### Plugin Config

         "platform": "LevoitHumidifiers"
        },
        {
            "name": "Levoit Air Purifiers",
            "email": "abcdefg@gmail.com",
            "password": "abcdefg",
            "experimentalFeatures": [
                "Humidifiers"
            ],
            "_bridge": {
                "username": "abcdefg",
                "port": 37728
            },

### Plugin Version

2.0.0

### Homebridge Version

1.7.0

### Node.js Version

20.9.0

### NPM Version

9.x

### Operating System

Synology

**Comment by RaresAil** [comment]
Hey, this issue is from home app, in order to allow the values from the slider to be the same as in VeSync, this issue appears in home app
