### ISSUE TITLE
Missing Air purifier characteristic 

### ISSUE THREAD

**Issue by Sir-Ian** [RaresAil/homebridge-levoit-air-purifier#82]
### Describe The Bug

Nightlight won’t show any logs because it’s not being imported. It’s a separate function on the device itself, controlling an entirely different light than the “display”. 

Sorry for brevity, on mobile. 

### Expected behavior

Toggle On

### Logs

N/A

### Plugin Config

N/A

### Plugin Version

N/A

### Homebridge Version

N/A

### Node.js Version

N/A

### NPM Version

N/A

### Operating System

N/A

**Comment by RaresAil** [comment]
Dublicate of #76
