### ISSUE TITLE
Request for new

### ISSUE THREAD

**Issue by Silas888** [RaresAil/homebridge-levoit-air-purifier#83]
### Describe The Bug

Requesting support for the Levoit EverestAir model

### Expected behavior

N/a

### Logs

N/a

### Plugin Config

Plugin Config

{
"name": "Levoit Air Purifiers",
"email": "",
"password": "",
"_bridge": {
"username": "0E:A8:70:B3:CB:90",
"port": 43561
},
"platform": "LevoitAirPurifiers"
}

### Plugin Version

2.0

### Homebridge Version

4.52.1

### Node.js Version

16

### NPM Version

6.4

### Operating System

windows 11

**Comment by RaresAil** [comment]
Dublicate of #47 and don't have the unit to can add support
