### ISSUE TITLE
Support for Vital 200s

### ISSUE THREAD

**Issue by ianbholton** [RaresAil/homebridge-levoit-air-purifier#87]
### Describe The Bug

Support for Vital 200s Air Purifiers

### Expected behavior

N/a

### Logs

N/a

### Plugin Config

N/a

### Plugin Version

N/a

### Homebridge Version

N/a

### Node.js Version

N/a

### NPM Version

N/a

### Operating System

N/a

**Comment by Brandawg93** [comment]
#91

**Comment by slowpc1** [comment]
Thank you for the assist. Hopefully someone can look through it but to me it is looking good.

**Comment by RaresAil** [comment]
This should work in v3
