### ISSUE TITLE
300S | ioBroker.ham

### ISSUE THREAD

**Issue by Thomas-sketch** [RaresAil/homebridge-levoit-air-purifier#9]
I do not get any useful values

<html>
<body>

ham.0 | 2021-11-22 07:22:34.095 | info | stateChange ham.0.Hildegard-.Accessory-Information.Serial-Number {"val":"9c:9c:1f:32:65:aa","ack":true,"ts":1637565754093,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
-- | -- | -- | --
ham.0 | 2021-11-22 07:22:34.095 | info | stateChange ham.0.Hildegard-.Accessory-Information.Model {"val":"Core300S","ack":true,"ts":1637565754093,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:34.094 | info | stateChange ham.0.Hildegard-.Accessory-Information.Manufacturer {"val":"Levoit","ack":true,"ts":1637565754093,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:32.993 | info | stateChange ham.0.Edeltraud.Accessory-Information.Serial-Number {"val":"9c:9c:1f:32:86:5a","ack":true,"ts":1637565752991,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:32.993 | info | stateChange ham.0.Edeltraud.Accessory-Information.Model {"val":"Core300S","ack":true,"ts":1637565752991,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172364}
ham.0 | 2021-11-22 07:22:32.992 | info | stateChange ham.0.Edeltraud.Accessory-Information.Manufacturer {"val":"Levoit","ack":true,"ts":1637565752991,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172364}
ham.0 | 2021-11-22 07:22:29.993 | info | stateChange ham.0.Hildegard-.0000008D.Status-Tampered {"val":0,"ack":true,"ts":1637565749957,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.992 | info | stateChange ham.0.Hildegard-.0000008D.Status-Low-Battery {"val":0,"ack":true,"ts":1637565749957,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.988 | info | stateChange ham.0.Hildegard-.0000008D.Status-Fault {"val":0,"ack":true,"ts":1637565749957,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.988 | info | stateChange ham.0.Hildegard-.0000008D.Status-Active {"val":false,"ack":true,"ts":1637565749956,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.988 | info | stateChange ham.0.Hildegard-.0000008D.Name {"val":"","ack":true,"ts":1637565749956,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.988 | info | stateChange ham.0.Hildegard-.0000008D.VOC-Density {"val":0,"ack":true,"ts":1637565749956,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.987 | info | stateChange ham.0.Hildegard-.0000008D.Sulphur-Dioxide-Density {"val":0,"ack":true,"ts":1637565749956,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.987 | info | stateChange ham.0.Hildegard-.0000008D.PM2.5-Density {"val":0,"ack":true,"ts":1637565749956,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516582558}
ham.0 | 2021-11-22 07:22:29.987 | info | stateChange ham.0.Hildegard-.0000008D.PM10-Density {"val":0,"ack":true,"ts":1637565749956,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.987 | info | stateChange ham.0.Hildegard-.0000008D.Ozone-Density {"val":0,"ack":true,"ts":1637565749956,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.987 | info | stateChange ham.0.Hildegard-.0000008D.Nitrogen-Dioxide-Density {"val":0,"ack":true,"ts":1637565749956,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.984 | info | stateChange ham.0.Hildegard-.0000008D.PM2.5-Density {"val":2,"ack":true,"ts":1637565749956,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637565749956}
ham.0 | 2021-11-22 07:22:29.984 | info | stateChange ham.0.Hildegard-.0000008D.Air-Quality {"val":1,"ack":true,"ts":1637565749956,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173589}
ham.0 | 2021-11-22 07:22:29.984 | info | stateChange ham.0.Hildegard-.000000BB.Swing-Mode {"val":0,"ack":true,"ts":1637565749956,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516912888}
ham.0 | 2021-11-22 07:22:29.984 | info | stateChange ham.0.Hildegard-.000000BB.Rotation-Speed {"val":0,"ack":true,"ts":1637565749956,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516582554}
ham.0 | 2021-11-22 07:22:29.984 | info | stateChange ham.0.Hildegard-.000000BB.Name {"val":"","ack":true,"ts":1637565749956,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.984 | info | stateChange ham.0.Hildegard-.000000BB.Lock-Physical-Controls {"val":0,"ack":true,"ts":1637565749956,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173589}
ham.0 | 2021-11-22 07:22:29.982 | info | stateChange ham.0.Hildegard-.000000BB.Filter-Life-Level {"val":83,"ack":true,"ts":1637565749956,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173589}
ham.0 | 2021-11-22 07:22:29.982 | info | stateChange ham.0.Hildegard-.000000BB.Filter-Change-Indication {"val":0,"ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173589}
ham.0 | 2021-11-22 07:22:29.982 | info | stateChange ham.0.Hildegard-.000000BB.Rotation-Speed {"val":50,"ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637565749955}
ham.0 | 2021-11-22 07:22:29.982 | info | stateChange ham.0.Hildegard-.000000BB.Lock-Physical-Controls {"val":0,"ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173589}
ham.0 | 2021-11-22 07:22:29.982 | info | stateChange ham.0.Hildegard-.000000BB.Target-Air-Purifier-State {"val":1,"ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516271682}
ham.0 | 2021-11-22 07:22:29.981 | info | stateChange ham.0.Hildegard-.000000BB.Current-Air-Purifier-State {"val":2,"ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173589}
ham.0 | 2021-11-22 07:22:29.981 | info | stateChange ham.0.Hildegard-.000000BB.Active {"val":1,"ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516246642}
ham.0 | 2021-11-22 07:22:29.981 | info | stateChange ham.0.Hildegard-.Accessory-Information.Product-Data {"val":null,"ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.981 | info | stateChange ham.0.Hildegard-.Accessory-Information.Software-Revision {"val":"","ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.978 | info | stateChange ham.0.Hildegard-.Accessory-Information.Hardware-Revision {"val":"","ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.978 | info | stateChange ham.0.Hildegard-.Accessory-Information.Configured-Name {"val":"","ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.977 | info | stateChange ham.0.Hildegard-.Accessory-Information.App-Matching-Identifier {"val":null,"ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.975 | info | stateChange ham.0.Hildegard-.Accessory-Information.Accessory-Flags {"val":0,"ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.975 | info | stateChange ham.0.Hildegard-.Accessory-Information.Firmware-Revision {"val":"1.1.1","ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.975 | info | stateChange ham.0.Hildegard-.Accessory-Information.Serial-Number {"val":"9c:9c:1f:32:65:aa","ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.974 | info | stateChange ham.0.Hildegard-.Accessory-Information.Name {"val":"Hildegard ","ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.974 | info | stateChange ham.0.Hildegard-.Accessory-Information.Model {"val":"Core300S","ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.974 | info | stateChange ham.0.Hildegard-.Accessory-Information.Manufacturer {"val":"Levoit","ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516173588}
ham.0 | 2021-11-22 07:22:29.974 | info | stateChange ham.0.Edeltraud.0000008D.Status-Tampered {"val":0,"ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.973 | info | stateChange ham.0.Edeltraud.0000008D.Status-Low-Battery {"val":0,"ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.973 | info | stateChange ham.0.Edeltraud.0000008D.Status-Fault {"val":0,"ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.973 | info | stateChange ham.0.Edeltraud.0000008D.Status-Active {"val":false,"ack":true,"ts":1637565749955,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.973 | info | stateChange ham.0.Edeltraud.0000008D.Name {"val":"","ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.972 | info | stateChange ham.0.Edeltraud.0000008D.VOC-Density {"val":0,"ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.972 | info | stateChange ham.0.Edeltraud.0000008D.Sulphur-Dioxide-Density {"val":0,"ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.972 | info | stateChange ham.0.Edeltraud.0000008D.PM2.5-Density {"val":0,"ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516582553}
ham.0 | 2021-11-22 07:22:29.972 | info | stateChange ham.0.Edeltraud.0000008D.PM10-Density {"val":0,"ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.972 | info | stateChange ham.0.Edeltraud.0000008D.Ozone-Density {"val":0,"ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.972 | info | stateChange ham.0.Edeltraud.0000008D.Nitrogen-Dioxide-Density {"val":0,"ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.967 | info | stateChange ham.0.Edeltraud.0000008D.PM2.5-Density {"val":1,"ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637565749954}
ham.0 | 2021-11-22 07:22:29.967 | info | stateChange ham.0.Edeltraud.0000008D.Air-Quality {"val":1,"ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172380}
ham.0 | 2021-11-22 07:22:29.967 | info | stateChange ham.0.Edeltraud.000000BB.Swing-Mode {"val":0,"ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.967 | info | stateChange ham.0.Edeltraud.000000BB.Rotation-Speed {"val":0,"ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516582552}
ham.0 | 2021-11-22 07:22:29.967 | info | stateChange ham.0.Edeltraud.000000BB.Name {"val":"","ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.967 | info | stateChange ham.0.Edeltraud.000000BB.Lock-Physical-Controls {"val":0,"ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172370}
ham.0 | 2021-11-22 07:22:29.966 | info | stateChange ham.0.Edeltraud.000000BB.Filter-Life-Level {"val":87,"ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172370}
ham.0 | 2021-11-22 07:22:29.965 | info | stateChange ham.0.Edeltraud.000000BB.Filter-Change-Indication {"val":0,"ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172370}
ham.0 | 2021-11-22 07:22:29.965 | info | stateChange ham.0.Edeltraud.000000BB.Rotation-Speed {"val":75,"ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637565749954}
ham.0 | 2021-11-22 07:22:29.965 | info | stateChange ham.0.Edeltraud.000000BB.Lock-Physical-Controls {"val":0,"ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172370}
ham.0 | 2021-11-22 07:22:29.964 | info | stateChange ham.0.Edeltraud.000000BB.Target-Air-Purifier-State {"val":0,"ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172370}
ham.0 | 2021-11-22 07:22:29.964 | info | stateChange ham.0.Edeltraud.000000BB.Current-Air-Purifier-State {"val":2,"ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172370}
ham.0 | 2021-11-22 07:22:29.964 | info | stateChange ham.0.Edeltraud.000000BB.Active {"val":1,"ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.964 | info | stateChange ham.0.Edeltraud.Accessory-Information.Product-Data {"val":null,"ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.964 | info | stateChange ham.0.Edeltraud.Accessory-Information.Software-Revision {"val":"","ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.963 | info | stateChange ham.0.Edeltraud.Accessory-Information.Hardware-Revision {"val":"","ack":true,"ts":1637565749954,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.963 | info | stateChange ham.0.Edeltraud.Accessory-Information.Configured-Name {"val":"","ack":true,"ts":1637565749953,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.962 | info | stateChange ham.0.Edeltraud.Accessory-Information.App-Matching-Identifier {"val":null,"ack":true,"ts":1637565749953,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.962 | info | stateChange ham.0.Edeltraud.Accessory-Information.Accessory-Flags {"val":0,"ack":true,"ts":1637565749953,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.962 | info | stateChange ham.0.Edeltraud.Accessory-Information.Firmware-Revision {"val":"1.1.1","ack":true,"ts":1637565749953,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.962 | info | stateChange ham.0.Edeltraud.Accessory-Information.Serial-Number {"val":"9c:9c:1f:32:86:5a","ack":true,"ts":1637565749953,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172365}
ham.0 | 2021-11-22 07:22:29.962 | info | stateChange ham.0.Edeltraud.Accessory-Information.Name {"val":"Edeltraud","ack":true,"ts":1637565749953,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172364}
ham.0 | 2021-11-22 07:22:29.962 | info | stateChange ham.0.Edeltraud.Accessory-Information.Model {"val":"Core300S","ack":true,"ts":1637565749953,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172364}
ham.0 | 2021-11-22 07:22:29.961 | info | stateChange ham.0.Edeltraud.Accessory-Information.Manufacturer {"val":"Levoit","ack":true,"ts":1637565749953,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1637516172364}
ham.0 | 2021-11-22 07:22:29.834 | info | updateState Hildegard-.0000008D.Status-Tampered: value = 0 /common= {"type":"number","min":0,"max":1,"read":true,"write":false,"role":"value","name":"Status Tampered","unit":""}
ham.0 | 2021-11-22 07:22:29.833 | info | updateState Hildegard-.0000008D.Status-Low-Battery: value = 0 /common= {"type":"number","min":0,"max":1,"read":true,"write":false,"role":"value.lowbat","name":"Status Low Battery","unit":""}
ham.0 | 2021-11-22 07:22:29.833 | info | updateState Hildegard-.0000008D.Status-Active: value = false /common= {"type":"boolean","read":true,"write":false,"role":"sensor","name":"Status Active","unit":""}
ham.0 | 2021-11-22 07:22:29.833 | info | updateState Hildegard-.0000008D.VOC-Density: value = 0 /common= {"type":"number","min":0,"max":1000,"read":true,"write":false,"role":"value","name":"VOC Density","unit":""}
ham.0 | 2021-11-22 07:22:29.832 | info | updateState Hildegard-.0000008D.Sulphur-Dioxide-Density: value = 0 /common= {"type":"number","min":0,"max":1000,"read":true,"write":false,"role":"value","name":"Sulphur Dioxide Density","unit":""}
ham.0 | 2021-11-22 07:22:29.832 | info | updateState Hildegard-.0000008D.PM10-Density: value = 0 /common= {"type":"number","min":0,"max":1000,"read":true,"write":false,"role":"value","name":"PM10 Density","unit":""}
ham.0 | 2021-11-22 07:22:29.832 | info | updateState Hildegard-.0000008D.Nitrogen-Dioxide-Density: value = 0 /common= {"type":"number","min":0,"max":1000,"read":true,"write":false,"role":"value","name":"Nitrogen Dioxide Density","unit":""}
ham.0 | 2021-11-22 07:22:29.833 | info | updateState Hildegard-.0000008D.Name: value = /common= {"type":"string","read":true,"write":false,"role":"text","name":"Name","unit":""}
ham.0 | 2021-11-22 07:22:29.833 | info | updateState Hildegard-.0000008D.Status-Fault: value = 0 /common= {"type":"number","min":0,"max":1,"read":true,"write":false,"role":"value","name":"Status Fault","unit":""}
ham.0 | 2021-11-22 07:22:29.831 | info | updateState Hildegard-.0000008D.PM2.5-Density: value = 2 /common= {"type":"number","min":0,"max":1000,"read":true,"write":false,"role":"value","name":"PM2.5 Density","unit":""}
ham.0 | 2021-11-22 07:22:29.831 | info | updateChannel Hildegard-.0000008D: name =
ham.0 | 2021-11-22 07:22:29.832 | info | updateState Hildegard-.0000008D.Ozone-Density: value = 0 /common= {"type":"number","min":0,"max":1000,"read":true,"write":false,"role":"value","name":"Ozone Density","unit":""}
ham.0 | 2021-11-22 07:22:29.832 | info | updateState Hildegard-.0000008D.PM2.5-Density: value = 0 /common= {"type":"number","min":0,"max":1000,"read":true,"write":false,"role":"value","name":"PM2.5 Density","unit":""}
ham.0 | 2021-11-22 07:22:29.831 | info | updateState Hildegard-.000000BB.Swing-Mode: value = 0 /common= {"type":"number","min":0,"max":1,"read":true,"write":true,"role":"level","name":"Swing Mode","unit":""}
ham.0 | 2021-11-22 07:22:29.830 | info | updateState Hildegard-.000000BB.Name: value = /common= {"type":"string","read":true,"write":false,"role":"text","name":"Name","unit":""}
ham.0 | 2021-11-22 07:22:29.830 | info | updateState Hildegard-.000000BB.Filter-Life-Level: value = 83 /common= {"type":"number","min":0,"max":100,"read":true,"write":false,"role":"value","name":"Filter Life Level","unit":""}
ham.0 | 2021-11-22 07:22:29.831 | info | updateState Hildegard-.0000008D.Air-Quality: value = 1 /common= {"type":"number","min":0,"max":5,"read":true,"write":false,"role":"value","name":"Air Quality","unit":""}
ham.0 | 2021-11-22 07:22:29.830 | info | updateState Hildegard-.000000BB.Filter-Change-Indication: value = 0 /common= {"type":"number","min":0,"max":1,"read":true,"write":false,"role":"value","name":"Filter Change Indication","unit":""}
ham.0 | 2021-11-22 07:22:29.829 | info | updateState Hildegard-.000000BB.Lock-Physical-Controls: value = 0 /common= {"type":"number","min":0,"max":1,"read":true,"write":true,"role":"level","name":"Lock Physical Controls","unit":""}
ham.0 | 2021-11-22 07:22:29.830 | info | updateState Hildegard-.000000BB.Lock-Physical-Controls: value = 0 /common= {"type":"number","min":0,"max":1,"read":true,"write":true,"role":"level","name":"Lock Physical Controls","unit":""}
ham.0 | 2021-11-22 07:22:29.830 | info | updateState Hildegard-.000000BB.Rotation-Speed: value = 0 /common= {"type":"number","unit":"%","min":0,"max":100,"read":true,"write":true,"role":"level","name":"Rotation Speed"}
ham.0 | 2021-11-22 07:22:29.829 | info | updateState Hildegard-.000000BB.Target-Air-Purifier-State: value = 1 /common= {"type":"number","min":0,"max":1,"read":true,"write":true,"role":"level","name":"Target Air Purifier State","unit":""}
ham.0 | 2021-11-22 07:22:29.828 | info | updateState Hildegard-.000000BB.Active: value = 1 /common= {"type":"number","min":0,"max":1,"read":true,"write":true,"role":"level","name":"Active","unit":""}
ham.0 | 2021-11-22 07:22:29.828 | info | updateState Hildegard-.Accessory-Information.Product-Data: value = null /common= {"type":"string","read":true,"write":false,"role":"text","name":"Product Data","unit":""}
ham.0 | 2021-11-22 07:22:29.829 | info | updateState Hildegard-.000000BB.Rotation-Speed: value = 50 /common= {"type":"number","unit":"%","min":0,"max":100,"read":true,"write":true,"role":"level","name":"Rotation Speed"}
ham.0 | 2021-11-22 07:22:29.827 | info | updateState Hildegard-.Accessory-Information.Software-Revision: value = /common= {"type":"string","read":true,"write":false,"role":"text","name":"Software Revision","unit":""}
ham.0 | 2021-11-22 07:22:29.827 | info | updateState Hildegard-.Accessory-Information.Configured-Name: value = /common= {"type":"string","read":true,"write":true,"role":"text","name":"Configured Name","unit":""}
ham.0 | 2021-11-22 07:22:29.828 | info | updateChannel Hildegard-.000000BB: name =
ham.0 | 2021-11-22 07:22:29.828 | info | updateState Hildegard-.000000BB.Current-Air-Purifier-State: value = 2 /common= {"type":"number","min":0,"max":2,"read":true,"write":false,"role":"value","name":"Current Air Purifier State","unit":""}
ham.0 | 2021-11-22 07:22:29.827 | info | updateState Hildegard-.Accessory-Information.App-Matching-Identifier: value = null /common= {"type":"string","read":true,"write":false,"role":"text","name":"App Matching Identifier","unit":""}
ham.0 | 2021-11-22 07:22:29.826 | info | updateState Hildegard-.Accessory-Information.Firmware-Revision: value = 1.1.1 /common= {"type":"string","read":true,"write":false,"role":"text","name":"Firmware Revision","unit":""}
ham.0 | 2021-11-22 07:22:29.826 | info | updateState Hildegard-.Accessory-Information.Name: value = Hildegard /common= {"type":"string","read":true,"write":false,"role":"text","name":"Name","unit":""}
ham.0 | 2021-11-22 07:22:29.826 | info | updateState Hildegard-.Accessory-Information.Manufacturer: value = Levoit /common= {"type":"string","read":true,"write":false,"role":"text","name":"Manufacturer","unit":""}
ham.0 | 2021-11-22 07:22:29.827 | info | updateState Hildegard-.Accessory-Information.Hardware-Revision: value = /common= {"type":"string","read":true,"write":false,"role":"text","name":"Hardware Revision","unit":""}
ham.0 | 2021-11-22 07:22:29.825 | info | updateState Hildegard-.Accessory-Information.Identify: value = false /common= {"type":"boolean","read":false,"write":true,"role":"button","name":"Identify","unit":""}
ham.0 | 2021-11-22 07:22:29.826 | info | updateState Hildegard-.Accessory-Information.Model: value = Core300S /common= {"type":"string","read":true,"write":false,"role":"text","name":"Model","unit":""}
ham.0 | 2021-11-22 07:22:29.826 | info | updateState Hildegard-.Accessory-Information.Serial-Number: value = 9c:9c:1f:32:65:aa /common= {"type":"string","read":true,"write":false,"role":"text","name":"Serial Number","unit":""}
ham.0 | 2021-11-22 07:22:29.826 | info | updateState Hildegard-.Accessory-Information.Accessory-Flags: value = 0 /common= {"type":"number","min":0,"max":4294967295,"read":true,"write":false,"role":"value","name":"Accessory Flags","unit":""}
ham.0 | 2021-11-22 07:22:29.825 | info | updateChannel Hildegard-.Accessory-Information: name =
ham.0 | 2021-11-22 07:22:29.825 | info | updateDev Hildegard-: name = Hildegard /type= 1
ham.0 | 2021-11-22 07:22:29.822 | info | updateState Edeltraud.0000008D.Status-Tampered: value = 0 /common= {"type":"number","min":0,"max":1,"read":true,"write":false,"role":"value","name":"Status Tampered","unit":""}
ham.0 | 2021-11-22 07:22:29.822 | info | updateState Edeltraud.0000008D.Status-Fault: value = 0 /common= {"type":"number","min":0,"max":1,"read":true,"write":false,"role":"value","name":"Status Fault","unit":""}
ham.0 | 2021-11-22 07:22:29.822 | info | updateState Edeltraud.0000008D.Status-Active: value = false /common= {"type":"boolean","read":true,"write":false,"role":"sensor","name":"Status Active","unit":""}
ham.0 | 2021-11-22 07:22:29.821 | info | updateState Edeltraud.0000008D.VOC-Density: value = 0 /common= {"type":"number","min":0,"max":1000,"read":true,"write":false,"role":"value","name":"VOC Density","unit":""}
ham.0 | 2021-11-22 07:22:29.821 | info | updateState Edeltraud.0000008D.PM2.5-Density: value = 0 /common= {"type":"number","min":0,"max":1000,"read":true,"write":false,"role":"value","name":"PM2.5 Density","unit":""}
ham.0 | 2021-11-22 07:22:29.822 | info | updateState Edeltraud.0000008D.Status-Low-Battery: value = 0 /common= {"type":"number","min":0,"max":1,"read":true,"write":false,"role":"value.lowbat","name":"Status Low Battery","unit":""}
ham.0 | 2021-11-22 07:22:29.821 | info | updateState Edeltraud.0000008D.PM10-Density: value = 0 /common= {"type":"number","min":0,"max":1000,"read":true,"write":false,"role":"value","name":"PM10 Density","unit":""}
ham.0 | 2021-11-22 07:22:29.821 | info | updateState Edeltraud.0000008D.Sulphur-Dioxide-Density: value = 0 /common= {"type":"number","min":0,"max":1000,"read":true,"write":false,"role":"value","name":"Sulphur Dioxide Density","unit":""}
ham.0 | 2021-11-22 07:22:29.821 | info | updateState Edeltraud.0000008D.Name: value = /common= {"type":"string","read":true,"write":false,"role":"text","name":"Name","unit":""}
ham.0 | 2021-11-22 07:22:29.820 | info | updateState Edeltraud.0000008D.Ozone-Density: value = 0 /common= {"type":"number","min":0,"max":1000,"read":true,"write":false,"role":"value","name":"Ozone Density","unit":""}

</body>
</html>

**Comment by RaresAil** [comment]
Hey, what do you mean?

**Comment by RaresAil** [comment]
Related to this issue you opened some time ago (https://github.com/RaresAil/homebridge-levoit-air-purifier/issues/1), if this plugin doesn't work with ioBroker, than is nothing i can do.
