### ISSUE TITLE
After update to v3.x the device dosen't shutdown 

### ISSUE THREAD

**Issue by HackyPaddy** [RaresAil/homebridge-levoit-air-purifier#94]
### Describe The Bug

After the update to version 3.x the device (300S), i can not switch off the device over homekit. 
Automations also no longer work.

Everything works except deactivating / shut off the device.

### Expected behavior

---

### Logs

No abnormalities in the log

### Plugin Config

Version 2.x worked perfectly - The error occurred with the update to 3.x.

### Plugin Version

3.0

### Homebridge Version

1.7.0

### Node.js Version

18.19.0

### NPM Version

n/a

### Operating System

Raspberry

**Comment by RaresAil** [comment]
Thank you for reporting, i will take care of it

**Comment by moorew** [comment]
Can confirm - same issue for me

`[4/14/2024, 7:38:00 AM] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.`

**Comment by FlorentinTh** [comment]
Hi there, 
The bug is still happening for core300s with version 3.0.1 on Homebridge 1.8.4.

I use the following config: 

```json
{
    "name": "Levoit Air Purifiers",
    "email": "",
    "password": "",
    "experimentalFeatures": [
        "DeviceDisplay"
    ],
    "_bridge": {
        "username": "",
        "port": 33319
    },
    "platform": "LevoitAirPurifiers"
}
```

Logs output : 

> [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.

> [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
